<?php
$clubs = [
    'impuls' => [
        [
            'name' => 'Impuls',
            'adress' =>'VIENUOLIO G. 4',
            'city' => 'Vilnius',
            'sauna' => true,
            'soliarium' => true,
            'food-service' => true,
        ],
        [
            'name' => 'Impuls',
            'adress' =>'KAREIVIŲ G. 14',
            'city' => 'Vilnius',
            'sauna' => true,
            'soliarium' => true,
            'food-service' => false,
        ],
        [
            'name' => 'Impuls',
            'adress' =>'OZO G. 41',
            'city' => 'Kaunas',
            'sauna' => true,
            'soliarium' => false,
            'food-service' => true,
        ],
        [
            'name' => 'Impuls',
            'adress' =>'SAVANORIŲ PR. 28',
            'city' => 'Kaunas',
            'sauna' => true,
            'cross-training' => true,
            'food-service' => false,
        ],
        [
            'name' => 'Impuls',
            'adress' =>'TRINAPOLIO G. 11',
            'city' => 'Klaipeda',
            'sauna' => true,
            'soliarium' => false,
            'food-service' => true,
        ],
    ],
    'lemon_gym' => [
        [
            'name' => 'Lemon Gym',
            'adress' =>'Antakalnis',
            'city' => 'Vilnius',
            'sauna' => false,
            'soliarium' => true,
            'food-service' => false,
        ],
        [
            'name' => 'Lemon Gym',
            'adress' =>'Banginis',
            'city' => 'Vilnius',
            'sauna' => true,
            'soliarium' => true,
            'food-service' => false,
        ],
        [
            'name' => 'Lemon Gym',
            'adress' =>'Europa',
            'city' => 'Kaunas',
            'sauna' => true,
            'soliarium' => true,
            'food-service' => true,
        ],
        [
            'name' => 'Lemon Gym',
            'adress' =>'Perkunkiemis',
            'city' => 'Klaipeda',
            'sauna' => false,
            'soliarium' => false,
            'food-service' => true,
        ],
    ],
    'gym+' => [
        [
            'name' => 'Gym+',
            'adress' =>'Kalvarijų g. 88',
            'city' => 'Vilnius',
            'sauna' => true,
            'soliarium' => true,
            'food-service' => false,
        ],
        [
            'name' => 'Gym+',
            'adress' =>'Žemaitės g. 22',
            'city' => 'Vilnius',
            'sauna' => true,
            'soliarium' => true,
            'food-service' => false,
        ],
        [
            'name' => 'Gym+',
            'adress' =>'Gedimino pr. 9',
            'city' => 'Kaunas',
            'sauna' => true,
            'soliarium' => true,
            'food-service' => false,
        ],
        [
            'name' => 'Gym+',
            'adress' =>'Ukmergės g. 256',
            'city' => 'Kaunas',
            'sauna' => true,
            'soliarium' => true,
            'food-service' => false,
        ],
        [
            'name' => 'Gym+',
            'adress' =>'Dariaus ir Girėno g. 2',
            'city' => 'Klaipeda',
            'sauna' => true,
            'soliarium' => true,
            'food-service' => false,
        ],
    ],
];